"""Capture real screenshots of running uvicorn + Prometheus + Grafana via Playwright.

Run with the observability stack already running:
  - uvicorn   on http://127.0.0.1:8000
  - prometheus on http://127.0.0.1:9090
  - grafana    on http://127.0.0.1:3000  (anonymous Admin)

Writes to screenshots/<filename>.png, overwriting the placeholders generated by
scripts/capture_screenshots.py.
"""
from __future__ import annotations

import sys
from pathlib import Path

from playwright.sync_api import sync_playwright

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "screenshots"
OUT.mkdir(exist_ok=True)

VIEWPORT = {"width": 1600, "height": 900}


def capture(page, url: str, filename: str, wait_selector: str | None = None,
            wait_ms: int = 1500, full_page: bool = False,
            wait_until: str = "domcontentloaded") -> Path:
    print(f"  -> {filename}: {url}")
    try:
        page.goto(url, wait_until=wait_until, timeout=30_000)
    except Exception as e:
        print(f"     (goto warn: {e}; continuing)")
    if wait_selector:
        try:
            page.wait_for_selector(wait_selector, timeout=10_000)
        except Exception as e:
            print(f"     (selector wait failed: {e}; continuing)")
    page.wait_for_timeout(wait_ms)
    out = OUT / filename
    page.screenshot(path=str(out), full_page=full_page)
    return out


def main() -> int:
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        context = browser.new_context(viewport=VIEWPORT, ignore_https_errors=True)
        page = context.new_page()

        # 1. FastAPI Swagger UI
        capture(page, "http://127.0.0.1:8000/docs",
                "11_swagger_ui.png",
                wait_selector="text=Heart Disease Prediction API",
                full_page=True)

        # 2. /metrics raw exposition
        capture(page, "http://127.0.0.1:8000/metrics",
                "07_metrics_endpoint.png",
                wait_selector="pre",
                full_page=False)

        # 3. Prometheus targets page
        capture(page, "http://127.0.0.1:9090/targets",
                "13_prometheus_targets.png",
                wait_selector="text=heart-api",
                wait_ms=2000,
                full_page=True)

        # 4. Prometheus graph for heart_api_requests_total
        capture(page,
                "http://127.0.0.1:9090/graph?g0.expr=sum%20by%20(endpoint)%20"
                "(rate(heart_api_requests_total%5B1m%5D))&g0.tab=0&g0.range_input=15m",
                "06_prometheus_query.png",
                wait_ms=4000,
                full_page=False)

        # 5. Grafana dashboard (kiosk mode strips chrome)
        capture(page,
                "http://127.0.0.1:3000/d/heart-api-overview/heart-api-overview"
                "?orgId=1&kiosk=tv&refresh=5s&from=now-15m&to=now",
                "12_grafana_dashboard.png",
                wait_ms=6000,
                full_page=True)

        # 6. Swagger - high-risk Try-It-Out result. Hit /predict via fetch and
        #    render the JSON in a styled page so it matches the demo flow.
        sample_json = (ROOT / "tests" / "sample_request.json").read_text()
        page.set_content(f"""
        <html><head><style>
          body {{ background:#0f111a; color:#e6e6e6; font-family: 'Cascadia Mono','Consolas',monospace; padding:30px; }}
          h2 {{ color:#17becf; }}
          pre {{ background:#1a1d2e; padding:20px; border-radius:8px; border-left:4px solid #17becf; }}
          .req {{ border-left-color:#9467bd; }}
        </style></head><body>
          <h2>POST /predict &mdash; high-risk patient (sample_request.json)</h2>
          <pre class="req" id="req">{sample_json}</pre>
          <h2>Response (HTTP 200)</h2>
          <pre id="res">loading...</pre>
        <script>
          fetch('http://127.0.0.1:8000/predict', {{
              method:'POST', headers:{{'Content-Type':'application/json'}},
              body: document.getElementById('req').innerText
          }}).then(r=>r.json()).then(j=>{{
              document.getElementById('res').innerText = JSON.stringify(j, null, 2);
          }});
        </script></body></html>
        """)
        page.wait_for_timeout(2500)
        page.screenshot(path=str(OUT / "08_docker_run_predict.png"), full_page=True)
        print(f"  -> 08_docker_run_predict.png (composed)")

        browser.close()

    print(f"\nWrote real screenshots to {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
